In [3]:
import numpy as mat  
# матрицы  
matrix_1 = mat.array([[9, 2, 4], [7, 5, -5], [6, -2, 3]])  
matrix_2 = mat.array([[8, 2, 4], [0, 1, -3], [-2, 1, 6]]) 
matrix_3 = mat.array([[-2, 0], [4, 8],[1, -1]])
#сложение матриц
print(matrix_1 + matrix_2) 

[[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]


In [4]:
#вычитание матриц
print(matrix_2 - matrix_1) 

[[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]


In [5]:
#умножение первой и третьей матрицы
result = mat.dot(matrix_1, matrix_3)  
print(result) 

[[ -6  12]
 [  1  45]
 [-17 -19]]


In [6]:
#умножение первой матрицы на вторую затем на третью
result = mat.dot(matrix_1, matrix_2) 
result_2 = mat.dot(result, matrix_3) 
print(result_2) 

[[ 22 138]
 [-93 129]
 [ 16  56]]
