In [32]:
import numpy as mat  
# матрицы
matrix_1 = mat.array([[1, 2, 4], [7, 5, -2], [-2, 1, 3]])  
matrix_2 = mat.array([[-1, 0, 3], [2, -6, 1], [-7, 1, 5]]) 
matrix_3 = mat.array([[-2, 3], [4, 0],[7, -1]])
#сложение матриц
print(matrix_1 + matrix_2) 

[[ 0  2  7]
 [ 9 -1 -1]
 [-9  2  8]]


In [33]:
#вычитание матриц
print(matrix_2 - matrix_1) 

[[ -2  -2  -1]
 [ -5 -11   3]
 [ -5   0   2]]


In [35]:
#умножение первой и третьей матрицы
result = mat.dot(matrix_1, matrix_3)  
print(result) 

[[34 -1]
 [-8 23]
 [29 -9]]


In [36]:
#умножение первой матрицы на вторую затем на третью
result = mat.dot(matrix_1, matrix_2) 
result_2 = mat.dot(result, matrix_3) 
print(result_2) 

[[ 193 -100]
 [ -50   35]
 [  92  -61]]
